CREATE TABLE COLLEGE(
        COLLEGE_ID      NUMBER(11,0),
        COLLEGE_NAME    VARCHAR(30),
        CREATE_DATE     DATE DEFAULT SYSDATE,
        MODIFY_DATE     DATE DEFAULT SYSDATE,
        CONSTRAINT COLLEGE_PK PRIMARY KEY (COLLEGE_ID)
)

CREATE TABLE DEPARTMENT(
        DEPARTMENT_ID       NUMBER(11,0),
        DEPARTMENT_NAME     VARCHAR(30),
        COLLEGE_ID          NUMBER(11,0),
        CREATE_DATE         DATE DEFAULT SYSDATE,
        MODIFY_DATE         DATE DEFAULT SYSDATE,
        CONSTRAINT DEPARTMENT_PK PRIMARY KEY (DEPARTMENT_ID),
        CONSTRAINT DEPARTMENT_FK FOREIGN KEY (COLLEGE_ID) REFERENCES COLLEGE(COLLEGE_ID)
)

CREATE TABLE BUILDING(
        BUILDING_ID         NUMBER(11,0),
        BUILDING_NAME       VARCHAR(30),
        COLLEGE_ID          NUMBER(11,0),
        LOCATION            VARCHAR(30),
        CREATE_DATE         DATE DEFAULT SYSDATE,
        MODIFY_DATE         DATE DEFAULT SYSDATE,
        CONSTRAINT BUILDING_PK PRIMARY KEY (BUILDING_ID),
        CONSTRAINT BUILDING_FK FOREIGN KEY (COLLEGE_ID) REFERENCES COLLEGE(COLLEGE_ID)
)

CREATE TABLE COURSE(
        COURSE_ID           NUMBER(11,0),
        COURSE_TITLE        VARCHAR(50),
        SUBJECT             VARCHAR(30),
        CATALOG_NUMBER      NUMBER(6,0),
        SECTION             VARCHAR(6),
        COMPONENT           VARCHAR(6),
        DEPARTMENT_ID       NUMBER(11,0),
        CAPACITY            NUMBER(3,0),
        CREATE_DATE         DATE DEFAULT SYSDATE,
        MODIFY_DATE         DATE DEFAULT SYSDATE,
        CONSTRAINT COURSE_PK PRIMARY KEY (COURSE_ID),
        CONSTRAINT COURSE_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
)

CREATE TABLE LECTURER(
        LECTURER_ID         NUMBER(11,0),
        LECTURER_NAME       VARCHAR(30),
        DEPARTMENT_ID       NUMBER(11,0),
        CONTACT_NUMBER      NUMBER(11,0),
        EMAIL               VARCHAR(30),
        ADDRESS             VARCHAR(50),
        CREATE_DATE         DATE DEFAULT SYSDATE,
        MODIFY_DATE         DATE DEFAULT SYSDATE,
        CONSTRAINT LECTURER_PK PRIMARY KEY (LECTURER_ID),
        CONSTRAINT LECTURER_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
)

CREATE TABLE COURSE_LECTURER_LINE(
        CL_ID               NUMBER(11,0),
        COURSE_ID           NUMBER(11,0),
        LECTURER_ID         NUMBER(11,0),
        CREATE_DATE         DATE DEFAULT SYSDATE,
        MODIFY_DATE         DATE DEFAULT SYSDATE,
        CONSTRAINT CL_PK PRIMARY KEY (CL_ID),
        CONSTRAINT CL_FK1 FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID),
        CONSTRAINT CL_FK2 FOREIGN KEY (LECTURER_ID) REFERENCES LECTURER(LECTURER_ID)
)

CREATE TABLE TIMESLOT(
        TIMESLOT_ID         NUMBER(11,0),
        CL_ID               NUMBER(11,0),
        DAY                 VARCHAR(11),
        START_TIME          VARCHAR2(11),
        END_TIME            VARCHAR2(11),
        CREATE_DATE         DATE DEFAULT SYSDATE,
        MODIFY_DATE         DATE DEFAULT SYSDATE,
        CONSTRAINT TIMESLOT_PK PRIMARY KEY (TIMESLOT_ID),
        CONSTRAINT TIMESLOT_FK FOREIGN KEY (CL_ID) REFERENCES COURSE_LECTURER_LINE(CL_ID)
)

CREATE TABLE ROOM_TYPE(
        ROOM_TYPE_ID         NUMBER(11,0),
        ROOM_TYPE_NAME      VARCHAR(30),
        CREATE_DATE         DATE DEFAULT SYSDATE,
        MODIFY_DATE         DATE DEFAULT SYSDATE,
        CONSTRAINT ROOM_TYPE_PK PRIMARY KEY (ROOM_TYPE_ID)
)

CREATE TABLE ROOM(
        ROOM_ID         NUMBER(11,0),
        ROOM_NAME      VARCHAR(30),
        BUILDING_ID         NUMBER(11,0),
        ROOM_TYPE_ID         NUMBER(11,0),
        CAPACITY        NUMBER(3,0),
        CREATE_DATE         DATE DEFAULT SYSDATE,
        MODIFY_DATE         DATE DEFAULT SYSDATE,
        CONSTRAINT ROOM_PK PRIMARY KEY (ROOM_ID),
        CONSTRAINT ROOM_FK1 FOREIGN KEY (BUILDING_ID) REFERENCES BUILDING(BUILDING_ID),
        CONSTRAINT ROOM_FK2 FOREIGN KEY (ROOM_TYPE_ID) REFERENCES ROOM_TYPE(ROOM_TYPE_ID)
)

CREATE TABLE ROOM_SCHEDULE(
        ROOM_SCHEDULE_ID    NUMBER(11,0),
        ROOM_ID             NUMBER(11,0),
        DAY                 VARCHAR(11),
        START_TIME          VARCHAR2(11),
        END_TIME            VARCHAR2(11),
        CREATE_DATE         DATE DEFAULT SYSDATE,
        MODIFY_DATE         DATE DEFAULT SYSDATE,
        CONSTRAINT ROOM_SCHEDULE_PK PRIMARY KEY (ROOM_SCHEDULE_ID),
        CONSTRAINT ROOM_SCHEDULE_FK FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID)
)

CREATE TABLE RESERVATION(
        RESERVATION_ID      NUMBER(11,0),
        TIMESLOT_ID         NUMBER(11,0),
        ROOM_SCHEDULE_ID    NUMBER(11,0),
        SEMESTER            VARCHAR(11),
        ACADEMIC_YEAR       VARCHAR(20),
        DAY                 VARCHAR(11),
        START_TIME          VARCHAR2(11),
        END_TIME            VARCHAR2(11),
        STATUS              VARCHAR(11),
        CREATE_DATE         DATE DEFAULT SYSDATE,
        MODIFY_DATE         DATE DEFAULT SYSDATE,
        CONSTRAINT RESERVATION_PK PRIMARY KEY (RESERVATION_ID),
        CONSTRAINT RESERVATION_FK1 FOREIGN KEY (TIMESLOT_ID) REFERENCES TIMESLOT(TIMESLOT_ID),
        CONSTRAINT RESERVATION_FK2 FOREIGN KEY (ROOM_SCHEDULE_ID) REFERENCES ROOM_SCHEDULE(ROOM_SCHEDULE_ID)
)

CREATE TABLE PRIORITY(
        PRIORITY_ID         NUMBER(11,0),
        ROOM_ID             NUMBER(11,0),
        VALUE               NUMBER(6,0),
        CREATE_DATE         DATE DEFAULT SYSDATE,
        MODIFY_DATE         DATE DEFAULT SYSDATE,
        CONSTRAINT PRIORITY_PK PRIMARY KEY (PRIORITY_ID),
        CONSTRAINT PRIORITY_FK FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID)
)

CREATE TABLE AMENITY(
        AMENITY_ID         NUMBER(11,0),
        AMENITY_NAME        VARCHAR(30),
        CREATE_DATE         DATE DEFAULT SYSDATE,
        MODIFY_DATE         DATE DEFAULT SYSDATE,
        CONSTRAINT AMENITY_PK PRIMARY KEY (AMENITY_ID)
)

CREATE TABLE ROOM_AMENITY_LINE(
        ROOM_ID             NUMBER(11,0),
        AMENITY_ID          NUMBER(11,0),
        CREATE_DATE         DATE DEFAULT SYSDATE,
        MODIFY_DATE         DATE DEFAULT SYSDATE,
        CONSTRAINT ROOM_AMENITY_LINE_PK PRIMARY KEY (ROOM_ID,AMENITY_ID)
)

INSERT INTO COLLEGE (COLLEGE_ID, COLLEGE_NAME)VALUES (1,'College of Arts and Sciences')

SELECT * FROM COLLEGE

COMMIT;